branch-defaults:
  dams-add-travel-estimate-to-ruby:
    environment: rails-beanstalk-env
    group_suffix: null
global:
  application_name: get-moving-rails
  default_ec2_keyname: null
  default_platform: Ruby 2.2 (Puma)
  default_region: us-east-1
  profile: null
  sc: git
